### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by Victor239** [an-anime-team/anime-games-launcher#13]
The Releases section says to check the README, but there's nothing in the README than mentions Flatpak.

**Comment by retrozinndev** [comment]
The launcher is integrated in the `launcher.moe` remote. Run this command to add it to flatpak:
Note: If you want to apply these changes for system-wide, remove the `--user` flag.
```
flatpak remote-add --if-not-exists --user launcher.moe https://gol.launcher.moe/gol.launcher.moe.flatpakrepo
```
Then install it:
```
flatpak install launcher.moe moe.launcher.anime-games-launcher
```
Please, let me know if this helped you!

**Comment by Victor239** [comment]
Thanks, worked great! Is this ever going on Flathub btw?

**Comment by retrozinndev** [comment]
I think not, the _anime game company_ wouldn't be happy about this :/ 
But, yes, I would like it going to flathub.

**Comment by Victor239** [comment]
Fair enough!
