### ISSUE TITLE
Installation Errors for Honkai Impact 3rd and Honkai Star Rail on Linux

### ISSUE THREAD

**Issue by ToastKiste21** [an-anime-team/anime-games-launcher#18]
The installation process for both Honkai Impact 3rd and Honkai Star Rail fails with a runtime error, specifically indicating an inability to request jadeite metadata and returning a 'Bad Gateway' response. No such issues occur while installing Genshin Impact.

System Information:

    Operating System: Arch Linux - Plasma Wayland
    System Specs: R9 7950X, AMD RX 7900 XT
[debug.log](https://github.com/an-anime-team/anime-games-launcher/files/15132109/debug.log)
![Screenshot_20240426_164452](https://github.com/an-anime-team/anime-games-launcher/assets/87302692/936e032f-a1b0-4ad4-a946-84e264dbe806)

**Comment by retrozinndev** [comment]
There's a duplicate in the Discord server: [Failed to request Jadeite metadata](https://discordapp.com/channels/910869215857217596/1212962355076403301/1212962355076403301). See if it helps you out.
