### ISSUE TITLE
Stupid question: How to uninstall an installed game from the launcher?

### ISSUE THREAD

**Issue by c02y** [an-anime-team/anime-games-launcher#19]
Right now, I have to delete the directory in `~/.local/share/anime-games-launcher/games/`

**Comment by retrozinndev** [comment]
So, the launcher really doesn't have a function to uninstall a game. Currently, as you said, the only way is deleting the game's folder in the `~/.local/share/anime-games-launcher/games`. The launcher developer's working on it, but I do not know when it's going to release. **Please note that the universal launcher is still experimental, meaning its not ready for everyday use**.
