### ISSUE TITLE
Can't compile launcher

### ISSUE THREAD

**Issue by retrozinndev** [an-anime-team/anime-games-launcher#29]
I was curious to test the new launcher UI, so I tried compiling it, but unfortunately, I can't.
Cargo builds the app correctly, but when I run, the binary says that something was not found:
![image](https://github.com/user-attachments/assets/467255c1-1edf-4b43-82a2-6ee8d63b9568)
Output in text:
```txt
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/anime-games-launcher`
Error: No such file or directory (os error 2)
```

**Comment by krypt0nn** [comment]
Don't even know what to say -_-

**Comment by retrozinndev** [comment]
If other people run into this same issue, just create the launcher directory in `$HOME/.local/share/anime-games-launcher`.
